name: json_rpc_2_client
description: A client for JSON-RPC 2.0 protocol. Specs at https://www.jsonrpc.org/specification.
version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: 0.12.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
