name: json_rpc_2_client
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Bruno Bellissimo <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
